#SERVER
ACTIVE_PROFILE: dev
SERVER_PORT: 8011
CONTAINER_PORT: 8011


#OPENAI
OPEN_AI_KEY: default_secret



#DATASOURSE
MYSQL_USER: root
MYSQL_PASSWORD: root1/@
MYSQL_DATABASE: manageapp
MYSQL_URL: jdbc:mysql://${HOST_SERVER}:${MYSQL_PORT_MAPPER}/${MYSQL_DATABASE}
MYSQL_PORT: 3306
MYSQL_PORT_MAPPER: 3066
DB_HOST: localhost


#EMAIL CONFIG
EMAIL_HOST: localhost
EMAIL_PORT: 1025
EMAIL_ID: sidofdountio@gmail.com
EMAIL_PASSWORD: sa

COMPANY_EMAIL: sidof@gmail.com
#JWT
JWT_SECRET: S0GFIJ4pfv7yOVfz3SSHR+CnMe194SVaAW4zxkl+x3fLrMSW/0LuGkrL+SrSdr28olCjsI1nbqB5truczFbcoA==
EXPIRATION: 86400000

#FRONTEND
HOST_SERVER: localhost
ANGULAR_PORT: 30007
VERIFY_EMAIL_HOST: http://localhost${SERVER_PORT}
CONFIRMATION_ACCOUNT_URL: http://${HOST_SERVER}:${ANGULAR_PORT}/activation-account?token=
PASSWORD_URL: http://${HOST_SERVER}:${ANGULAR_PORT}/reset-password?token=

ACTIVATION_URL: http://${HOST_SERVER}:${ANGULAR_PORT}/activation-account
CUSTOMER_ORDER_URL: http://${HOST_SERVER}:${ANGULAR_PORT}/service/customer-invoice
ORIGIN: http://localhost:9000/api/v1/manager-app